automation:
  - alias: Motion detected in empty home
    id: motion_detected_in_empty_home
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor, binary_sensor.living_room_motion_sensor, binary_sensor.kitchen_motion_sensor, binary_sensor.bathroom_motion_sensor
      to: 'on'
    # - platform: state
    #   entity_id: binary_sensor.living_room_motion_sensor
    #   to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_select.home_preset
        state: "Empty"
      - condition: template
        value_template: '{{ states("vacuum.rockrobo") != "cleaning" }}'
      # - condition: state
      #   entity_id: vacuum.rockrobo
      #   state: "Empty"
    action:
    - service: notify.push_to_chrome_nizm0_oneplus3
      data_template:
        title: Somone wolking in empty home
        message: >
          Motiot detected in: {{ trigger.to_state.attributes.friendly_name }}