sensor:
  - platform: moon
  # - platform: rozkladzik
  #   city: 'wroclaw'
  #   stops:
  #     - id: 4507
  #       name: 'Home'
  #     - id: 1515
  #       name: 'Work'

  - platform: mold_indicator
    indoor_temp_sensor: sensor.living_room_temperature
    indoor_humidity_sensor: sensor.living_room_humidity
    outdoor_temp_sensor: sensor.dark_sky_temperature
    # outdoor_temp_sensor: sensor.flower_2_temperature
    calibration_factor: 1.0

# luftdaten:
#   sensor_id: 2303
#   show_on_map: false
#   sensors:
#     monitored_conditions:
#       - P1
#       - P2
      # - temperature
      # - humidity
      # - pressure
air_quality:
  - platform: opensensemap
    station_id: 5902649c5ba9e50011fc57b8

  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
      # - cn
    latitude: !secret home_latitude
    longitude: !secret home_longitude
  #  radius: 500
    show_on_map: false

binary_sensor:

  # - platform: impk
  #   monitored_conditions:
  #     - news
  - platform: template
    sensors:
      taking_bath:
        friendly_name: Taking bath
        device_class: occupancy
        value_template: >-
          {{ (states('sensor.bathroom_humidity')|float > states('sensor.average_house_humidity')|float + 10) and states('binary_sensor.bathroom_motion_sensor') == on}}
  - platform: bayesian
    name: In bed
    prior: 0.1
    probability_threshold: 0.8
    observations:
      # - entity_id: 'binary_sensor.hallway_motion_sensor'
      #   prob_given_true: 0.8
      #   prob_given_false: 0.3
      #   platform: 'state'
      #   to_state: 'off'
      # - entity_id: 'binary_sensor.living_room_motion_sensor'
      #   prob_given_true: 0.8
      #   prob_given_false: 0.3
      #   platform: 'state'
      #   to_state: 'off'
      - entity_id: binary_sensor.desctop_pc
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: media_player.philips_tv
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: group.all_devices  # device_tracker.google_maps_104688658658376260645
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'
      # - entity_id: device_tracker.google_maps_109218123589188227395
      #   prob_give_true: 0.7
      #   prob_give_false: 0.7
      #   platform: 'state'
      #   to_state: 'home'
      - entity_id: 'sun.sun'
        prob_given_true: 0.7
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'below_horizon'

input_select:
  home_preset:
    options:
    - Empty
    - Visitors
    - Alone
    initial: Empty

input_number:
  temp_min:
    name: Min temp
    # initial: 20
    min: 1
    max: 30
    step: 1
    mode: box
  temp_max:
    name: Max temp
    # initial: 30
    min: 20
    max: 50
    step: 1
    mode: box
  slider1:
    name: Numeric Input lider
    initial: 30
    min: 0
    max: 100
    step: 1
  max_temp_recorded:
    name: Max recorded temparature in home
    max: 50
    min: 20

input_datetime:
  both_date_and_time:
    name: Alarm Clock
    has_date: true
    has_time: true
    # initial: '{{datetime.datetime.now().strftime('%Y-%m-%d %H:%M'))}}'

automation:
  - alias: Notify when temperature is to hight or to low
    id: notify_when_temperature_is_to_hight_or_to_low
    initial_state: 'true'
    trigger:
      platform: state
      entity_id:
      - sensor.bedroom_temperature
      - sensor.living_room_temperature
      - sensor.kitchen_temperature
      - sensor.bathroom_temperature
      - sensor.kids_temperature
    condition:
      - condition: template
        value_template: '{{ (trigger.to_state.state > states.input_number.temp_max.state or trigger.to_state.state < states.input_number.temp_min.state) and trigger.to_state.state != "unavailable" and trigger.to_state.state > 0}}'
    action:
      - service: notify.push_to_chrome
        data_template:
          message: "Temperature {{ trigger.to_state.state }} in {{ trigger.to_state.attributes.friendly_name }} and is out of demaded params"
          title: "Problem with Teperature in {{ trigger.to_state.attributes.friendly_name }}"
          data:
            tag: 'room_{{trigger.to_state.attributes.friendly_name}}_temp'
  - alias: Notify on sun change
    id: notify_on_sun_change
    initial_state: 'true'
    trigger:
    - event: sunrise
      platform: sun
    - event: sunset
      platform: sun
    action:
      - service: notify.push_to_chrome
        data_template:
          message: >
            We have {{ trigger.event }}
          title: Sun is changin state
          data:
            tag: sun-state-change

  - alias: Motion detected in empty home
    id: motion_detected_in_empty_home
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_sensor, binary_sensor.living_room_motion_sensor, binary_sensor.kitchen_motion_sensor, binary_sensor.bathroom_motion_sensor
      to: 'on'
    # - platform: state
    #   entity_id: binary_sensor.living_room_motion_sensor
    #   to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_select.home_preset
        state: "Empty"
      - condition: template
        value_template: '{{ states("vacuum.rockrobo") != "cleaning" }}'
      # - condition: state
      #   entity_id: vacuum.rockrobo
      #   state: "Empty"
    action:
    - service: notify.push_to_chrome_nizm0_oneplus3
      data_template:
        title: Somone wolking in empty home
        message: >
          Motiot detected in: {{ trigger.to_state.attributes.friendly_name }}