sensor:
  - platform: moon
  - platform: season
  # - platform: rozkladzik
  #   city: 'wroclaw'
  #   stops:
  #     - id: 4507
  #       name: 'Home'
  #     - id: 1515
  #       name: 'Work'

  - platform: mold_indicator
    indoor_temp_sensor: sensor.living_room_temperature
    indoor_humidity_sensor: sensor.living_room_humidity
    outdoor_temp_sensor: sensor.dark_sky_temperature
    # outdoor_temp_sensor: sensor.flower_2_temperature
    calibration_factor: 1.0

  # - platform: airvisual
  #   api_key: !secret airvisual_api_key
  #   monitored_conditions:
  #     - us
  #     # - cn
  #   latitude: !secret home_latitude
  #   longitude: !secret home_longitude
  #   #  radius: 500
  #   show_on_map: false

  - platform: meteoalarm_m
    id: 'PL0264-Wroclaw'
    name: alert
    scan_interval: 3600

# luftdaten:
#   sensor_id: 2303
#   show_on_map: false
#   sensors:
#     monitored_conditions:
#       - P1
#       - P2
# - temperature
# - humidity
# - pressure
air_quality:
  - platform: opensensemap
    station_id: 5902649c5ba9e50011fc57b8

binary_sensor:
  # - platform: tod
  #   name: Early Morning
  #   after: sunrise
  #   after_offset: '-02:00'
  #   before: '07:00'
  # - platform: tod
  #   name: Late Morning
  #   after: '10:00'
  #   before: '12:00'
  # - platform: impk
  #   monitored_conditions:
  #     - news

  # - platform: template
  #   sensors:
  #     taking_bath:
  #       friendly_name: Taking bath
  #       device_class: occupancy
  #       value_template: >-
  #         {{ (states('sensor.bathroom_humidity')|float > states('sensor.average_house_humidity')|float + 10) and states('binary_sensor.bathroom_motion_sensor') == on}}
  - platform: bayesian
    name: In bed
    prior: 0.1
    probability_threshold: 0.8
    observations:
      # - entity_id: 'binary_sensor.hallway_motion_sensor'
      #   prob_given_true: 0.8
      #   prob_given_false: 0.3
      #   platform: 'state'
      #   to_state: 'off'
      # - entity_id: 'binary_sensor.living_room_motion_sensor'
      #   prob_given_true: 0.8
      #   prob_given_false: 0.3
      #   platform: 'state'
      #   to_state: 'off'
      - entity_id: binary_sensor.desctop_pc
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: "state"
        to_state: "off"
      - entity_id: media_player.philips_tv
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: "state"
        to_state: "off"
      - entity_id: group.family # device_tracker.google_maps_104688658658376260645
        prob_given_true: 0.7
        prob_given_false: 0.2
        platform: "state"
        to_state: "home"
      # - entity_id: device_tracker.google_maps_109218123589188227395
      #   prob_give_true: 0.7
      #   prob_give_false: 0.7
      #   platform: 'state'
      #   to_state: 'home'
      - entity_id: "sun.sun"
        prob_given_true: 0.7
        prob_given_false: 0.5
        platform: "state"
        to_state: "below_horizon"

input_select:
  home_preset:
    options:
      - Empty
      - Visitors
      - Alone
    initial: Empty

input_number:
  temp_min:
    name: Min temp
    # initial: 20
    min: 1
    max: 30
    step: 1
    mode: box
  temp_max:
    name: Max temp
    # initial: 30
    min: 20
    max: 50
    step: 1
    mode: box
  slider1:
    name: Numeric Input lider
    initial: 30
    min: 0
    max: 100
    step: 1
  max_temp_recorded:
    name: Max recorded temparature in home
    max: 50
    min: 20

input_datetime:
  both_date_and_time:
    name: Alarm Clock
    has_date: true
    has_time: true
    # initial: '{{datetime.datetime.now().strftime('%Y-%m-%d %H:%M'))}}'

automation:
  - alias: Notify when temperature is to hight or to low
    id: 4141ad64-5424-4d1c-8ade-7f5531a96e6b
    initial_state: "true"
    trigger:
      platform: state
      entity_id:
        - sensor.bedroom_temperature
        - sensor.living_room_temperature
        - sensor.kitchen_temperature
        - sensor.bathroom_temperature
        - sensor.kids_temperature
    condition:
      - condition: template
        value_template: '{{ (trigger.to_state.state|float > states.input_number.temp_max.state|float or trigger.to_state.state|float < states.input_number.temp_min.state|float) and trigger.to_state.state != "unavailable" and trigger.to_state.state|float > 0}}'
    action:
      - service: notify.mobile_app_nizm0_oneplus_8t
        data_template:
          message: Temperature {{ trigger.to_state.state }} in {{ trigger.to_state.attributes.friendly_name }} and is out of demanded params ({{states('sensor.date_time_iso')}})
          title: Problem with Temperature in {{ trigger.to_state.attributes.friendly_name }}
          data:
            tag: room_{{trigger.to_state.attributes.friendly_name}}_temp
            group: Home
      # - service: persistent_notification.create
      #   data_template:
      #     message: "({{states('sensor.date_time_iso')}}) Temperature {{ trigger.to_state.state }} in {{ trigger.to_state.attributes.friendly_name }} and is out of demanded params"
      #     title: "Problem with Temperature in {{ trigger.to_state.attributes.friendly_name }}"
  - alias: Notify on humidifier water level drop below 25mm
    id: eaf6df25-1c46-40fa-bc8c-34e22cfcde0f
    initial_state: "true"
    trigger:
      - platform: numeric_state
        entity_id: sensor.humidifier_water_level
        below: 25
    condition: []
    action:
      - service: notify.mobile_app_nizm0_oneplus_8t
        data_template:
          message: Please fill the humidiefier befor it can continue
          title: Water level in himidifier is to low
          data:
            tag: humidifier
            group: Home
      - service: fan.turn_off
        entity_id: fan.air_humidifier
  
  - alias: Notify on sun change
    id: b301f9f6-1f06-4858-b04c-8a0e3b5956d2
    initial_state: "true"
    trigger:
      - event: sunrise
        platform: sun
      - event: sunset
        platform: sun
    action:
      - service: notify.mobile_app_nizm0_oneplus_8t
        data_template:
          message: >
            We have {{ trigger.event }}
          title: Sun is changing state
          data:
            tag: sun-state-change
            group: Home

  - alias: Motion detected in empty home
    id: adfcc93b-5a94-4a6c-8fcb-84acbdf8597d
    initial_state: "true"
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor, binary_sensor.living_room_motion_sensor, binary_sensor.kitchen_motion_sensor, binary_sensor.bathroom_motion_sensor
        to: "on"
    # - platform: state
    #   entity_id: binary_sensor.living_room_motion_sensor
    #   to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.family
          state: "not_home"
        - condition: state
          entity_id: input_select.home_preset
          state: "Empty"
        - condition: template
          value_template: '{{ states("vacuum.rockrobo") != "cleaning" }}'
      # - condition: state
      #   entity_id: vacuum.rockrobo
      #   state: "Empty"
    action:
      - service: notify.mobile_app_nizm0_oneplus_8t
        data_template:
          title: Someone walking in empty home
          message: >
            Motion detected in: {{ trigger.to_state.attributes.friendly_name }} ({{ states('sensor.date_time_iso') }})
          data:
            # channel: motion
            group: HomeSecurity
            ttl: 0
            priority: high
            color: red #'#2DF56D'

  # - alias: Turn off all light when home is empty after restart
  #   id: ff79109b-b88c-4987-a361-b2b422335a24
  #   initial_state: 'true'
  #   trigger:
  #     - event: start
  #       platform: homeassistant
  #   action:
  #     - 