- platform: miflora
  mac: 'C4:7C:8D:66:CC:49'
  name: Flower 1
  force_update: false
  # median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:66:CC:34'
  name: Flower 2
  force_update: false
  # median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery