- platform: gearbest
  currency: USD
  items:
    # - id: 659226
    #   name: Xiaomi Aqara Human Body Sensor
    # - url: https://www.gearbest.com/alarm-systems/pp_659226.html
    #   name: Xiaomi Aqara Human Body Sensor
    # - url: https://www.gearbest.com/smart-lighting/pp_1664464.html
    #   name: Xiaomi Yeelight White
    # - url: https://www.gearbest.com/smart-lighting/pp_424884.html
    #   name: Yeelight Smart Light Strip
    # - url: https://www.gearbest.com/access-control/pp_626703.html
    #   name: Xiaomi Aqara Door Window Sensor
    - url: https://www.gearbest.com/access-control/pp_626695.html
      name: Xiaomi Aqara Smart Wireless Switch
    - url: https://www.gearbest.com/smart-light-bulb/pp_257679.html
      name: Xiaomi Smart Button
    - url: https://www.gearbest.com/smart-home-controls/pp_009661787808.html?wid=1433363
      name: Aqara Smart Vibration Sensor
    - url: https://www.gearbest.com/smart-lighting/pp_1032313.html
      name: Xiaomi Bedside Lamp
    - url: https://www.gearbest.com/smart-home-controls/pp_255607.html
      name: Broadlink RM Pro