- platform: moon
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
  # - type: since_last_boot
# - platform: command_line
#   name: SSL cert expiry
#   unit_of_measurement: days
#   scan_interval: 10800
#   command: "ssl-cert-check -b -c /ssl/fullchain.pem | awk '{ print $NF }'"
- platform: travisci
  api_key: !secret travisapi
  scan_interval: 3600
  repository: Home-Assistant-Config
  branch: hassio
  monitored_conditions: 
    - last_build_state
    - last_build_id
    - last_build_duration
    - state
- platform: cert_expiry
  host: has.nizmo.eu
  name: LetsEncrypt
- platform: airvisual
  api_key: !secret airvisual_api_key
  monitored_conditions:
    - us
    - cn
  latitude: !secret home_latitude
  longitude: !secret home_longitude
#  radius: 500
  show_on_map: false
- platform: mold_indicator
  indoor_temp_sensor: sensor.living_room_temperature
  indoor_humidity_sensor: sensor.living_room_humidity
  outdoor_temp_sensor: sensor.dark_sky_temperature
  # outdoor_temp_sensor: sensor.flower_2_temperature
  calibration_factor: 1.0

# - platform: seventeentrack
#   username: !secret 17_track_user
#   password: !secret 17_track_pass

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
  - 1
  monitored_conditions:
  - summary
#  - minutely_summary
  - hourly_summary
  - daily_summary
#  - icon
#  - nearest_storm_distance
#  - nearest_storm_bearing
  - precip_type
  - precip_intensity
  - precip_probability
  - temperature
  - apparent_temperature
  - dew_point
  - wind_speed
  - wind_bearing
  - cloud_cover
  - humidity
  - pressure
  - visibility
  - ozone
# - platform: darksky
#   api_key: !secret darksky_api_key
#   forecast:
#   - 1
#   - 2
#   - 3
#   - 4
#   - 5
#   monitored_conditions:
#     - icon
#     - summary
#     - nearest_storm_distance
#     - nearest_storm_bearing
#     - humidity
#     - temperature
#     - temperature_high
#     - temperature_low
#     - apparent_temperature
#     - apparent_temperature_high
#     - apparent_temperature_low
#     - wind_speed
#     - wind_bearing
#     - precip_type
#     - precip_probability
#     - precip_accumulation
#     - precip_intensity
#     - precip_intensity_max
#     - uv_index
#     - daily_summary
#     - pressure
#     - visibility
#   update_interval:
#     minutes: 5

# - platform: yr
#   name: Weather
#   forecast: 1
#   monitored_conditions:
#   - temperature
#   - symbol
#   - precipitation
#   - windSpeed
#   - pressure
#   - windDirection
#   - humidity
#   - fog
#   - cloudiness
#   - lowClouds
#   - mediumClouds
#   - highClouds
#   - dewpointTemperature