sensor:
  - platform: history_stats
    name: Nizm0 week work
    entity_id: person.nizm0 #nizmo
    state: 'Work'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Nizm0 today at work
    entity_id: person.nizm0 #nizmo
    state: 'Work'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Gosia parents
    entity_id: person.gosia #gosia
    state: 'GP'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: TV is on
    entity_id: media_player.philips_tv
    state: 'on'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: TV is idle(app runing)
    entity_id: media_player.philips_tv
    state: 'idle'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Netflix is on
    entity_id: sensor.philips_tv_media_title
    state: 'Netflix'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: PS4 is on
    entity_id: media_player.playstation_4
    state: 'on'
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
    
  - platform: template
    sensors:
      philips_tv_media_title:
        friendly_name: "Philips TV Media Title"
        value_template: "{{ state_attr('media_player.philips_tv', 'media_title') }}"

  - platform: history_stats
    name: Wasmachine Vibrations
    entity_id: binary_sensor.washer_vibration
    state: 'on'
    type: 'count'
    end: '{{ now() }}'
    duration:
      minutes: 10

  # - platform: statistics
  #   entity_id: device_tracker.nizmo_phone
  # - platform: statistics
  #   entity_id: device_tracker.gosia_phone
    # max_age:
    #   minutes: 30
  - platform: min_max
    name: average_house_humidity
    type: mean
    entity_ids:
      - sensor.bedroom_humidity
      - sensor.living_room_humidity
      - sensor.kids_humidity
      - sensor.kitchen_humidity
  - platform: min_max
    name: average_house_temperature
    type: mean
    entity_ids:
      - sensor.bedroom_temperature
      - sensor.living_room_temperature
      - sensor.kids_temperature
      - sensor.kitchen_temperature
  - platform: min_max
    name: Max temperature in home
    type: max
    entity_ids:
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.living_room_temperature
      - sensor.kids_temperature
      - sensor.kitchen_temperature
  - platform: tauron_amiplus
    name: Tauron AMIPlus
    username: !secret tauron_amiplus.username
    password: !secret tauron_amiplus.password
    energy_meter_id: !secret tauron_amiplus.energy_meter_id
    check_generation: true
    monitored_variables:
      - zone
      - consumption_daily
      - consumption_monthly
      - consumption_yearly
      - generation_daily
      - generation_monthly
      - generation_yearly