sensor:
  - platform: history_stats
    name: Vibrations in last 10 min
    entity_id: sensor.tilt_and_vibration_sensor_action
    state: "vibration"
    type: "count"
    end: "{{ now() }}"
    duration:
      minutes: 10

  # - platform: statistics
  #   entity_id: device_tracker.nizmo_phone
  # - platform: statistics
  #   entity_id: device_tracker.gosia_phone
  # max_age:
  #   minutes: 30
  - platform: min_max
    name: average_house_humidity
    type: mean
    entity_ids:
      - sensor.bedroom_multi_sensor_humidity
      - sensor.living_room_multi_sensor_humidity
      - sensor.kids_multi_sensor_humidity
      - sensor.kitchen_multi_sensor_humidity
      - sensor.hallway_multi_sensor_humidity
  - platform: min_max
    name: average_house_temperature
    type: mean
    round_digits: 2
    entity_ids:
      - sensor.bedroom_multi_sensor_temperature
      - sensor.living_room_multi_sensor_temperature
      - sensor.kids_multi_sensor_temperature
      - sensor.kitchen_multi_sensor_temperature
      - sensor.hallway_multi_sensor_temperature
  - platform: min_max
    name: Max temperature in home
    type: max
    entity_ids:
      - sensor.bedroom_multi_sensor_temperature
      - sensor.bathroom_multi_sensor_temperature
      - sensor.living_room_multi_sensor_temperature
      - sensor.kids_multi_sensor_temperature
      - sensor.kitchen_multi_sensor_temperature
      - sensor.hallway_multi_sensor_temperature
