- platform: mqtt
  state_topic: "tele/RF_Bridge/RESULT"
  command_topic: "cmnd/RF_Bridge/RfCode"
  name: Christmas tree test
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "#051533"
  payload_off: "#05153C"
  qos: 1
  retain: false
  optimistic: true