- platform: mqtt
  name: Light 1
  state_topic: "stat/d1mini-office/POWER1"
  command_topic: "cmnd/d1mini-office/POWER1"
  availability_topic: "tele/d1mini-office/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: false
- platform: mqtt
  name: Light 2
  state_topic: "stat/d1mini-office/POWER2"
  command_topic: "cmnd/d1mini-office/POWER2"
  availability_topic: "tele/d1mini-office/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: false
- platform: mqtt
  name: Top Light
  state_topic: "stat/d1mini-office/POWER4"
  command_topic: "cmnd/d1mini-office/POWER4"
  availability_topic: "tele/d1mini-office/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: false