---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
homeassistant:

  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs

  # packages: !include_dir_named ../packages
  
  # whitelist_external_dirs:
  #   - /config

  # https://www.home-assistant.io/docs/authentication/providers/#trusted-networks
  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 192.168.1.0/24
  #       - 172.17.0.0/16
  #       - 172.30.32.0/23
  #       - 127.0.0.1
  #       - fd00::/8
  #   - type: homeassistant
