---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
homeassistant:

  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs

  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 116 #!secret home_elevation
  unit_system: metric
  time_zone: Europe/Warsaw
  # customize: !include customize.yaml