octoprint: !include_dir_list ../entities/octoprints

automation:
  - id: '1555699464312'
    alias: _octoprint finish
    trigger:
    - entity_id: binary_sensor.ender_3_printing
      from: 'on'
      platform: state
      to: 'off'
    condition: []
    action:
    - data:
        data:
          tag: Octoprint_tag
          group: Octoprint
        message: Printer just finished his work ({{states('sensor.date_time_iso')}})
        title: Printing finished
      service: notify.mobile_app_nizm0_oneplus3
    - delay: 0:2
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.ender_3_printing
          state: 'off'
    - service: switch.turn_off
      entity_id: switch.shelly_ender_3_switch
