---
# Sensors are gathering information about states and conditions.
#
# This loads up my sensor configurations
#
# https://www.home-assistant.io/components/sensor/
#
sensor: !include_dir_list ../entities/sensors

air_quality:
  - platform: opensensemap
    station_id: 5902649c5ba9e50011fc57b8