- id: '1550153327362'
  alias: _aHTML5 Clicked
  trigger:
  - event_data:
      event_data:
        action: open_door
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom_main_light
    service: light.turn_on
