- id: '1542570692649'
  alias: New Automation
  trigger:
  - above: '8'
    entity_id: sensor.nizm0_today_at_work
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.google_maps_104688658658376260645
    state: work
  action:
  - data:
      message: Test message
    service: notify.push_to_chrome
- id: '1546595642051'
  alias: SD card warning
  trigger:
  - above: '50'
    entity_id: sensor.disk_use_percent_home
    platform: numeric_state
  condition: []
  action:
  - data:
      title: SD Card usage is bigger than 50%
    service: notify.push_to_chrome
