- id: '1542570692649'
  alias: New Automation
  trigger:
  - above: '8'
    entity_id: sensor.nizm0_today_at_work
    platform: numeric_state
  condition:
  - condition: state
    entity_id: device_tracker.google_maps_104688658658376260645
    state: work
  action:
  - data:
      message: Test message
    service: notify.push_to_chrome
