- id: '1550153327362'
  alias: _aHTML5 Clicked
  trigger:
  - event_data:
      event_data:
        action: open_door
    event_type: html5_notification.clicked
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom_main_light
    service: light.turn_on
- id: '1555699464312'
  alias: _octoprint finish
  trigger:
  - entity_id: binary_sensor.ender_3_printing
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        tag: Octoprint_tag
      message: Printer just finished his work
      title: Printing finished
    service: notify.push_to_chrome
