- id: '1584744623104'
  alias: Decrease Living Room brightness
  description: ''
  trigger:
  - device_id: d73bbd2c276743ccad09ffa03908f1d0
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 15a7dd19261a492083929bbfeaa572b3
    domain: light
    entity_id: light.living_room
    type: brightness_decrease
- id: '1584744721754'
  alias: Increase Living Room brightness
  description: ''
  trigger:
  - device_id: d73bbd2c276743ccad09ffa03908f1d0
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 15a7dd19261a492083929bbfeaa572b3
    domain: light
    entity_id: light.living_room
    type: brightness_increase
  - condition: state
    entity_id: light.living_room_directional_light
    state: 'off'
  - data: {}
    entity_id: light.living_room_directional_light
    service: light.turn_on
- id: '1587510128209'
  alias: On line Drzzs
  description: ''
  trigger:
  - entity_id: sensor.drzzs
    from: offline
    platform: state
    to: streaming
  condition:
  - condition: device
    device_id: 610d7357fd8f008af8a1bd381840585a
    domain: device_tracker
    entity_id: device_tracker.nizm0_oneplus_8t
    type: is_home
  action:
  - data:
      entity_id: media_player.living_room_speaker
      message: Drzzs is now online
    service: tts.cloud_say
  mode: single
- id: '1590066631245'
  alias: Kitchen turn on light on motion on
  description: ''
  trigger:
  - device_id: 90da5d057bd74a93bf3ca888305d9db8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_motion_sensor
    platform: device
    type: motion
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      after_offset: -01:00:00
      condition: sun
    - below: 50
      condition: device
      device_id: 90da5d057bd74a93bf3ca888305d9db8
      domain: sensor
      entity_id: sensor.kitchen_illumination
      type: is_illuminance
  action:
  - device_id: 5a8b0915e5834d4b91341ea4a1c71f07
    domain: light
    entity_id: light.kitchen_top_light
    type: turn_on
  mode: single
- id: '1590066700654'
  alias: Kitchen turn off light on motion off
  description: ''
  trigger:
  - device_id: 90da5d057bd74a93bf3ca888305d9db8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_motion_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: 5a8b0915e5834d4b91341ea4a1c71f07
    domain: light
    entity_id: light.kitchen_top_light
    type: turn_off
  mode: single
- id: '1591536466380'
  alias: Turn on/off Living Room Directional Lights
  description: ''
  trigger:
  - entity_id: switch.living_room_switch_2
    platform: state
  condition: []
  action:
  - device_id: 15a7dd19261a492083929bbfeaa572b3
    domain: light
    entity_id: light.living_room_directional_light
    type: toggle
- id: '1599140047737'
  alias: PC Turn off on low power
  description: ''
  trigger:
  - below: 10
    device_id: 4adc54ca759f4d2085ba563f487cf2b3
    domain: sensor
    entity_id: sensor.bw_shp6_01_wattage
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: value
  condition: []
  action:
  - device_id: 4adc54ca759f4d2085ba563f487cf2b3
    domain: switch
    entity_id: switch.bw_shp6_01_relay
    type: turn_off
  mode: single
- id: '1599140148066'
  alias: PC Turn On switch 1 press
  description: ''
  trigger:
  - device_id: afbf7c1c12434200a39ea17187a21356
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_release
  condition: []
  action:
  - device_id: 4adc54ca759f4d2085ba563f487cf2b3
    domain: switch
    entity_id: switch.bw_shp6_01_relay
    type: turn_on
  mode: single
- id: '1599755142278'
  alias: PC Desk Lamp Togle when Pc is on
  description: ''
  trigger:
  - device_id: afbf7c1c12434200a39ea17187a21356
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  condition:
  - condition: device
    type: is_on
    device_id: 4adc54ca759f4d2085ba563f487cf2b3
    entity_id: switch.bw_shp6_01_relay
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 1
  action:
  - type: toggle
    device_id: 3367910d1a8549189a95361700983d6b
    entity_id: light.desctop_lamp
    domain: light
  mode: single
- id: '1607956116675'
  alias: Christmas lights turn on after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{% set n = now() %} {{ n.month == 12 and 14 <= n.day <= 31
        }}'
    - condition: template
      value_template: '{% set n = now() %} {{ n.month == 1 and 1 <= n.day <= 30 }}'
  action:
  - type: turn_on
    device_id: d98be1384fd94ccc9ea31d77accf8fd6
    entity_id: switch.bw_shp6_03_relay
    domain: switch
  - type: turn_on
    device_id: 243903ee717f1fa4bd16ce65c869f056
    entity_id: light.wled_christmas_tree
    domain: light
    brightness_pct: 100
  mode: single
- id: '1607956218820'
  alias: Christmas lights turn off after sunset
  description: ''
  trigger:
  - platform: time
    at: 01:00
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{% set n = now() %} {{ n.month == 12 and 14 <= n.day <= 31
        }}'
    - condition: template
      value_template: '{% set n = now() %} {{ n.month == 1 and 1 <= n.day <= 31 }}'
  action:
  - type: turn_off
    device_id: d98be1384fd94ccc9ea31d77accf8fd6
    entity_id: switch.bw_shp6_03_relay
    domain: switch
  - type: turn_off
    device_id: 243903ee717f1fa4bd16ce65c869f056
    entity_id: light.wled_christmas_tree
    domain: light
  mode: single
- id: '1611578959480'
  alias: PC Desk Lamp Off when Pc is on and Nizm0 Not in home
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e98572e3b2854cc59ef431dd0fd90928
    entity_id: light.desctop_lights
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: not
    conditions:
    - condition: device
      device_id: 610d7357fd8f008af8a1bd381840585a
      domain: device_tracker
      entity_id: device_tracker.nizm0_oneplus_8t
      type: is_home
  action:
  - type: turn_off
    device_id: 3367910d1a8549189a95361700983d6b
    entity_id: light.desctop_lamp
    domain: light
  mode: single
- id: '1612520803809'
  alias: portex.eu is unavailable
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.portexst_eu
    from: 'on'
    to: 'off'
    for: 00:05
  condition: []
  action:
  - service: notify.hangouts_portex
    data:
      title: portex.eu is down
      message: hey, something is wrong with internet access
  mode: single
