homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

api:
sun:
automation: !include_dir_merge_list automations/
cloud: !include cloud.yaml
config:
conversation:
# discovery:
frontend:
  themes: !include_dir_merge_named themes/
group: !include_dir_merge_named groups/
ifttt:
  key: !secret ifttt_key
logbook:
map:
notify: !include_dir_merge_list notify/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
shopping_list:
tts:
  - platform: google
updater:
zone: !include zones.yaml


# Enables support for tracking state changes over time
history: !include history.yaml

history_graph: !include history_graph.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  login_attempts_threshold: 3
  trusted_networks:
    - 192.168.1.0/24

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    ifttt.trigger: debug

shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bash/pullconfig.sh

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_getway1_key
      mac: !secret xiaomi_getway1_mac
      host: !secret xiaomi_getway1_ip

light:
  - platform: yeelight
    devices:
      192.168.1.3:
        name: bedroom_main_light
        transition: 10
        use_music_mode: true #(defaults to False)
        save_on_change: true #(defaults to True)

# chromcast
media_player:
  - platform: cast
    host: 192.168.1.46
    # name: Office Android Tv Philips
  - platform: gpmdp
    host: 192.168.1.100
    name: pc_gpmdp
  - platform: cast
    host: 192.168.1.47
    # name: Office Google Home Mini
  - platform: broadlink
    name: Office TV
    host: 192.168.1.51
    mac: 78:0F:77:00:6A:7D
    ircodes_ini: 'broadlink_media_codes/philips.ini'
    ping_host: 192.168.1.46

input_boolean:
  # battery_status_update:
  #   name: Battery Status Update
  kids_light:
    name: Main light
    icon: mdi:lightbulb
    initial: off

switch:
  - platform: broadlink
    host: 192.168.1.51
    mac: 78:0F:77:00:6A:7D
    switches:
      tv_philips:
        friendly_name: Philips TV Power
        command_on: "JgAqAFYfDR4ODw4PKy0NEA0QDRAODw4PDg8ODw4PDg8OEA0QHA8OHg4PDgANBQAAAAAAAAAAAAAAAAAA="
    togles:
      1:
        command_on: "JgAqAFkcEBwQDRANLSoQDRANEA0QDRAODw4QDRANEA0QDRANEA0QDRANHwANBQAAAAAAAAAAAAAAAAAA="
      2:
        command_on: "JgAsAFgcEBwQDRANEBsfDRANEA0QDRANEA4PDhANEA0QDRANEA0QDRANHxwPAA0FAAAAAAAAAAAAAAAA="
      3:
        command_on: "JgAqAFgcEBwQDRANLSoQDRANEA0QDRAODw4QDRANEA0QDRANEA0QDR8NEAANBQAAAAAAAAAAAAAAAAAA="
      4:
        command_on: "JgAsAFkcEBsQDg8ODxweDhANEA0QDRANEA0QDRAODw4PDhANEA0QDR4cEA0QAA0FAAAAAAAAAAAAAAAA="
      5:
        command_on: "JgAoAFkcEBsQDRAOLCsQDRANEA0QDRANEA0QDRANEA0QDhANEA0eHB4ADQU="
      6:
        command_on: "JgAsAFkcEBwQDRANEBsfDRANEA0QDRANEA4PDg8OEA0QDRANEA0QDR8NEBsQAA0FAAAAAAAAAAAAAAAA="
      7:
        command_on: "JgAqAFgdDx0ODw4PLCsPDg8ODw4PDg8ODw8ODw4PDg8PDg8ODw4dDw8ODwANBQAAAAAAAAAAAAAAAAAA="
      8:
        command_on: "JgAsAFYeDh4ODw4PDxwdDw4PEA4NEA0QDw4PDg8ODw4QDRANEA0eHQ8ODw4NAA0FAAAAAAAAAAAAAAAA="
      9:
        command_on: "JgAoAFceDR4OEA0QKi0NEA4PDg8ODw4PDg8ODw4QDRANEA0QHB4ODxwADQU="
      0:
        command_on: "JgAuAFgcDx0PDg8ODxweDg8OEA0QDRANEA4PDg8ODw4ODw8ODg8PDhANDg8OEA8ADQUAAAAAAAAAAAAA="
        # command_off: "JgAqAFYfDR4ODw4PKy0NEA0QDRAODw4PDg8ODw4PDg8OEA0QHA8OHg4PDgANBQAAAAAAAAAAAAAAAAAA="
# light:
#   - platform: template
#     lights:
#       kids_light:
#         icon: mdi:lightbulb
#         value_template: "{{ is_state('input_boolean.kids_light', 'on') }}"
#         value_template: "off"
#         initial: off
#         turn_on:
#           service: light.turn_on
#           data: 
#             entity_id: switch.kids_light
#         turn_off:
#           service: light.turn_off
#           data:
#             entity_id: switch.kids_light

# device tracking
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    mqtt_topic: "owntracks/#"
    events_only: True
    waypoint_whitelist:
      - Nizm0
      - Gosia
      - Tablet1
    region_mapping:
      cabin: home
      office: work
      kindergarden: kindergarden
      nursery: nursery
      mp: mp
      gp: gp
  - platform: tomato
    host: !secret tomato_ip
    username: !secret tomato_username
    password:  !secret tomato_password
    http_id: !secret tomato_http_id
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False

android_ip_webcam:
  - host: 192.168.1.17
    name: Office camera
    port: 8080
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      # - ffc # front camera
      - focus
      # - gps_active
      # - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
#   - host: 192.168.1.18
#     name: Kitchen Camera
#     port: 8080
#     sensors:
#       - audio_connections
#       - battery_level
#       - battery_temp
#       - battery_voltage
#       - light
#       - motion
#       - pressure
#       - proximity
#       - sound
#       - video_connections
#     switches:
#       - exposure_lock
#       - ffc # front camera
#       - focus
#       - gps_active
#       - night_vision
#       - overlay
#       - torch
#       - whitebalance_lock
#       - video_recording

mqtt:
  embedded:
# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   keepalive: 60
#   username: !secret mqtt_login
#   password: !secret mqtt_password
