homeassistant:
  # auth_providers:
  #   - type: homeassistant
    # - type: legacy_api_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml
api:
config:
http:
  # api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # login_attempts_threshold: 5
  # trusted_networks:
  #   - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# android_ip_webcam: !include configuration/android_ip_webcam.yaml
automation: !include_dir_merge_list configuration/automations/
cloud: !include configuration/cloud.yaml


device_tracker: !include configuration/device_tracker.yaml
frontend:
  themes: !include_dir_merge_named themes/
group: !include_dir_merge_named configuration/groups/
history: !include configuration/history.yaml
history_graph: !include configuration/history_graph.yaml
ifttt:
  key: !secret ifttt_key
input_boolean: !include configuration/input_boolean.yaml
logger:
  default: error
  logs:
    ifttt.trigger: debug
media_player: !include configuration/media_player.yaml
mqtt:
  broker: core-mosquitto
  username: !secret mosquitto_username
  password: !secret mosquitto_password
  discovery: true
notify: !include_dir_merge_list configuration/notify/
script: !include_dir_merge_named configuration/scripts/
sensor: !include_dir_merge_list configuration/sensors/
shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bash/pullconfig.sh
shopping_list:
switch: !include configuration/switch.yaml
zone: !include configuration/zone.yaml

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_getway1_key
      mac: !secret xiaomi_getway1_mac
      host: !secret xiaomi_getway1_ip

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.150
    name: rockrobo
    token: !secret xiaomi_rockrobo_key

binary_sensor:
  - platform: workday
    country: PL
    workdays: [mon, tue, wed, thu, fri]


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://has.nizmo.eu:3218
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: https://has.nizmo.eu:9541/devices
  nodered:
    title: Node-RED
    icon: mdi:shuffle-variant
    url: https://has.nizmo.eu:1880
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: https://has.nizmo.eu:3000


input_select:
  home_preset:
    options:
      - Empty
      - Visitors
      - Alone
    initial: Empty
input_number:
  temp_min:
    name: Min temp
    initial: 20
    min: 1
    max: 30
    step: 1
    mode: box
  temp_max:
    name: Max temp
    initial: 30
    min: 20
    max: 50
    step: 1
    mode: box
  slider1:
    name: Numeric Input lider
    initial: 30
    min: 0
    max: 100
    step: 1
input_datetime:
  both_date_and_time:
    name: Alarm Clock
    has_date: true
    has_time: true
    # initial: '{{datetime.datetime.now().strftime('%Y-%m-%d %H:%M'))}}'