homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

api:

sun:
automation: !include_dir_merge_named automations/
cloud:
config:
conversation:
discovery:
frontend:
  themes: !include_dir_merge_named themes/
group: !include_dir_merge_named groups/
ifttt:
  key: !secret ifttt_key
logbook:
map:
notify: !include_dir_merge_named notify/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_named sensors/
shopping_list:
tts:
  - platform: google
updater:
zone: !include zones.yaml


# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sun
      - sensor
      - switch
      - device_tracker
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  login_attempts_threshold: 3
  trusted_networks:
    - 192.168.1.0/24

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    ifttt.trigger: debug

shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bash/pullconfig.sh

xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_getway1_key
      # interface: 192.168.1.110
      mac: !secret xiaomi_getway1_mac

# chromcast
media_player:
  - platform: cast
    host: 192.168.1.46
    # name: Office Android Tv Philips
  - platform: gpmdp
    host: 192.168.1.100
    name: My Pc Google Play
  - platform: cast
    host: 192.168.1.47
    # name: Office Google Home Mini

input_boolean:
  battery_status_update:
    name: Battery Status Update
  kids_light:
    icon: mdi:lightbulb
    initial: off

# light:
#   - platform: template
#     lights:
#       kids_light:
#         icon: mdi:lightbulb
#         value_template: "{{ is_state('input_boolean.kids_light', 'on') }}"
#         value_template: "off"
#         initial: off
#         turn_on:
#           service: light.turn_on
#           data: 
#             entity_id: switch.kids_light
#         turn_off:
#           service: light.turn_off
#           data:
#             entity_id: switch.kids_light

# device tracking
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    mqtt_topic: "owntracks/#"
    events_only: True
    waypoint_whitelist:
      - Nizm0
      - Gosia
      - Tablet1
    region_mapping:
      cabin: home
      office: work
      kindergarden: kindergarden
      nursery: nursery
      mp: mp
      gp: gp
  - platform: tomato
    host: !secret tomato_ip
    username: !secret tomato_username
    password:  !secret tomato_password
    http_id: !secret tomato_http_id
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False

android_ip_webcam:
  - host: 192.168.1.29
    name: Office camera
    port: 8080
    sensors:
      - audio_connections
      # - battery_level
      # - battery_temp
      # - battery_voltage
      # - light
      # - motion
      # - pressure
      # - proximity
      # - sound
      - video_connections
    switches:
      - exposure_lock
      # - ffc # front camera
      - focus
      # - gps_active
      # - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
  
# mqtt
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  keepalive: 60
  username: !secret mqtt_login
  password: !secret mqtt_password