---
# Welcome to my Home Assistant configuration!
#
# Don't be scared by the size of my configuration file...
# It is probably the smallest you've ever seen.
#
# My system is very modular and very differently structured
# compared to other configurations you'll find online.
#
# Basically, each file in the repository does 1 (one, uno, eins)
# thing only! Click through it, you'll get it pretty fast.
#
# The configuration.yaml is only used to bootstrap the system.
#
homeassistant:
  # Load packages
  packages: !include_dir_named packages/integrations

# browser_mod:
#   devices:
#     a04bd448-beda43c5:
#       name: Chrome_PC
#     4e83d973-e8c99618:
#       name: Chrome_Work
#     d86b2fcd-d890ee26:
#       name: Chrome_OnePlus3
#     601a98ca-4ca18723:
#      name: Surface_1_Pro