homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

android_ip_webcam: !include configuration/android_ip_webcam.yaml
api:
automation: !include_dir_merge_list configuration/automations/
cloud: !include configuration/cloud.yaml
config:
conversation:
device_tracker: !include configuration/device_tracker.yaml
# discovery:
frontend:
  themes: !include_dir_merge_named themes/
group: !include_dir_merge_named configuration/groups/
history: !include configuration/history.yaml
history_graph: !include configuration/history_graph.yaml
ifttt:
  key: !secret ifttt_key
input_boolean: !include configuration/input_boolean.yaml
light: !include configuration/light.yaml
logbook:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    ifttt.trigger: debug
map:
media_player: !include configuration/media_player.yaml
mqtt:
  embedded:
notify: !include_dir_merge_list configuration/notify/
script: !include_dir_merge_named configuration/scripts/
sensor: !include_dir_merge_list configuration/sensors/
shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bash/pullconfig.sh
shopping_list:
sun:
switch: !include configuration/switch.yaml
tts:
  - platform: google
updater:
zone: !include configuration/zones.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  login_attempts_threshold: 5
  trusted_networks:
    - 192.168.1.0/24

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_getway1_key
      mac: !secret xiaomi_getway1_mac
      host: !secret xiaomi_getway1_ip
