homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
api:
config:
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
system_health:
person:
updater:
discovery:
  ignore:
    - yeelight
automation: !include automations.yaml
automation old: !include_dir_merge_list configuration/automations/
cloud: !include configuration/cloud.yaml
group: !include_dir_merge_named configuration/groups/

# ########################################
# ###                GUI               ###
# ########################################
conversation:
frontend:
  themes: !include_dir_merge_named themes/
map:

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://has.nizmo.eu:8321
  tasmoadmin:
    title: Tasmo Admin
    icon: mdi:lightbulb-on
    url: https://has.nizmo.eu:9541/devices
  # nodered:
  #   title: Node-RED
  #   icon: mdi:shuffle-variant
  #   url: https://has.nizmo.eu:1880
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: https://has.nizmo.eu:3000

custom_updater:
  track:
  - cards
  - components
  card_urls: 
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  # component_urls:
  # python_script_urls:

history_graph: !include configuration/history_graph.yaml

# ########################################
# ###              LOGGING             ###
# ########################################
logger:   
  default: error
  logs:
    # homeassistant.components.device_tracker: debug
    # google_maps: debug
    ifttt.trigger: debug
# View all events in a logbook
logbook:

history: !include configuration/history.yaml
recorder:
  purge_interval: 2
  purge_keep_days: 5
  # include:
  #   domains:
  #     - sensor
  #     - switch
  #     - media_player
  # exclude:
  #   domains:
  #   - device_tracker
  #   entities:
  #    - sensor.last_boot
  #    - sensor.date

# ########################################
# ###              ENTITIES             ###
# ########################################

input_boolean: !include configuration/input_boolean.yaml
light: !include_dir_merge_list configuration/light
plant: !include configuration/plants.yaml

script: !include_dir_merge_named configuration/scripts/
sensor: !include_dir_merge_list configuration/sensors/
switch: !include_dir_merge_list configuration/switch
device_tracker: !include configuration/device_tracker.yaml
media_player: !include configuration/media_player.yaml
zone: !include configuration/zone.yaml
weather:
- platform: darksky
  api_key: !secret darksky_api_key
  mode: hourly

input_select: !include_dir_merge_named configuration/inputs/input_select
input_number: !include_dir_merge_named configuration/inputs/input_number
input_datetime: !include_dir_merge_named configuration/inputs/input_datetime

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
shopping_list:
notify: !include_dir_merge_list configuration/notify/
ifttt:
  key: !secret ifttt_key

python_script:

ffmpeg:

tts:
  - platform: google

shell_command:
  get_latest_config: bash /home/hass/.homeassistant/bash/pullconfig.sh

xiaomi_aqara:
  discovery_retry: 5
  gateways:
  - key: !secret xiaomi_getway1_key
    mac: !secret xiaomi_getway1_mac
    host: !secret xiaomi_getway1_ip

vacuum:
- platform: xiaomi_miio
  host: 192.168.1.150
  name: Rockrobo
  token: !secret xiaomi_rockrobo_key

binary_sensor: !include configuration/binary_sensor.yaml
# fan:
#   - platform: xiaomi_miio
#     host: 192.168.1.9
#     token: !secret xiaomi_airpurifierr_key

# camera:
# - platform: ffmpeg
#   input: FFMPEG_SUPPORTED_INPUT
# - platform: xiaomi
#   name: Camera
#   host: '192.168.1.135'
#   model: 'yi'
#   password: '5547'
calendar:
  - platform: todoist
    token: !secret todois_api_key
    custom_projects:
    - name: 'All Projects'
    - name: 'Due Today'
      due_date_days: 0
    - name: 'Due This Week'
      due_date_days: 7
    # - name: 'Math Homework'
    #   labels:
    #     - Homework
      # include_projects:
      #   - Mathematical Structures II
      #   - Calculus II

# android_ip_webcam: !include configuration/android_ip_webcam.yaml

proximity:
  home_michal:
    zone: home
    devices:
      - device_tracker.google_maps_104688658658376260645
    tolerance: 50
    unit_of_measurement: km
  work_michal:
    zone: work
    devices:
      - device_tracker.google_maps_104688658658376260645
    tolerance: 50
    unit_of_measurement: km
  home_gosia:
    zone: home
    devices:
      - device_tracker.google_maps_109218123589188227395
    tolerance: 50
    unit_of_measurement: km