---
custom_header: !include lovelace/cards/custom_header.yaml
# resources: !include_dir_list lovelace/resources
# sidebar: !include lovelace/cards/sidebar.yaml
button_card_templates: !include lovelace/templates/button_card_templates.yaml

title: Manage
views:
  - !include lovelace/views/10_home.yaml
  - !include lovelace/views/100_testing.yaml
  - !include lovelace/views/104_manage.yaml
  - !include lovelace/views/105_stats.yaml