cch: !include lovelace/cards/compact_custom_header.yaml
resources: !include_dir_list lovelace/resources
title: Home
views:
  # - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/main.yaml
  - !include lovelace/views/home.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/kids.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/bathroom.yaml
  - !include lovelace/views/hallway.yaml
  - !include lovelace/views/family.yaml
  - !include lovelace/views/camera.yaml
  - !include lovelace/views/flowers.yaml
  - !include lovelace/views/testing.yaml
  - !include lovelace/views/floreplan.yaml
