- platform: nfandroidtv
  name: Living room TV
  host: 192.168.1.130

- name: pushbullet nizmo
  platform: pushbullet
  api_key: !secret pushbullet_api_key

- name: pushbullet gosia
  platform: pushbullet
  api_key: !secret pushbullet_api_key_gosia 

- name: push_to_chrome
  platform: html5
  gcm_api_key: !secret google_push_api_key
  gcm_sender_id: !secret google_push_sender_id

- name: hangouts
  platform: hangouts
  default_conversations:
    - id: UgwLFucuyD1KYDehqHp4AaABAQ