- platform: nfandroidtv
  name: Living room TV
  host: 192.168.1.130

- name: pushbullet nizmo
  platform: pushbullet
  api_key: !secret pushbullet_api_key

- name: pushbullet gosia
  platform: pushbullet
  api_key: !secret pushbullet_api_key_gosia 

# - name: push_to
#   platform: html5
#   gcm_api_key: !secret google_push_api_key
#   gcm_sender_id: !secret google_push_sender_id

- platform: html5
  name: push_to_chrome
  vapid_pub_key: !secret google_push_public_key
  vapid_prv_key: !secret google_push_priv_key
  vapid_email: !secret email

- name: hangouts
  platform: hangouts
  default_conversations:
    - id: UgwLFucuyD1KYDehqHp4AaABAQ