automation:
  - alias: Home door opened
    id: 2500790a-b412-4af1-bfc5-e5912827c55e
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.home_door_sensor
        to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: script.home_doors_has_been_opened
      - service: notify.push_to_chrome
        data_template: 
          message: >
            ({{states('sensor.date_time_iso')}})
            {% if is_state("group.family", "not_home") and is_state("input_select.home_preset", "empty") -%}
              Nobody is in home
            {%- else -%}
              "In home:"
              {% if is_state("person.nizm0", "home") -%}
                {{state_attr("person.nizm0", "friendly_name")}}
              {%- endif %}
              {% if is_state("person.gosia", "home") -%}
                {{state_attr("person.gosia", "friendly_name")}}
              {%- endif %}
            {%- endif %}
          title: Someone opened home doors
          data:
            icon: mdi:alert
            actions:
              - action: open
                icon: "/static/icons/favicon-192x192.png"
                title: Open Home Assistant
              - action: open_door
                title: Open door
            tag: 'home-door-notification'


  #### HOME DOOR CLOSED
  - alias: Home door closed
    id: 244aae0e-f9af-49d6-991b-2dd9c5e6f929
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.home_door_sensor
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hallway_motion_sensor
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: script.home_doors_has_been_closed

  - alias: Home door closed notification
    id: 5fce2f0f-c733-499a-889d-cd4b8b345e28
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.home_door_sensor
        from: 'on'
        to: 'off'
    action:
      - service: notify.push_to_chrome
        data_template:
          message: >
            ({{states('sensor.date_time_iso')}})
            Doors was open for: {{ trigger.from_state.attributes['Open since'] }} seconds 
          title: Dors are now closed
          data:
            actions:
              - action: open
                icon: "/static/icons/favicon-192x192.png"
                title: Open Home Assistant
              - action: open_door
                title: Open door
            tag: 'home-door-notification'