automation:
  - id: ac630c56-6eaa-45e5-9f71-db63e15032b6
    alias: Gosia entered the home
    initial_state: 'true'
    trigger: 
    - platform: zone
      entity_id: person.gosia # device_tracker.google_maps_109218123589188227395 #Gosia
      zone: zone.home
      event: enter
    condition:
    action: 
    - service: notify.mobile_app_nizm0_oneplus3
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
          ({{states('sensor.date_time_iso')}})
        title: Gosia entered the home
        data:
          tag: gosia-location-info
          group: Location
    - service: notify.hangouts
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
        title: Gosia entered the home