automation:
  - id: michal_is_out_from_work
    alias: Michał is out from Work
    initial_state: 'true'
    trigger: 
    - platform: zone
      entity_id: device_tracker.google_maps_104688658658376260645 #Nizm0
      zone: zone.work
      event: leave
      # for:
      #   minutes: 2
    condition:
    action:
    - service: notify.push_to_chrome
      data_template:
        message: >
          Current location: {{ state_attr('device_tracker.google_maps_104688658658376260645', 'address') }}
        title: Michał is out form work
        data:
          icon: https://lh4.googleusercontent.com/-s5iO7HHJJlM/AAAAAAAAAAI/AAAAAAAADC8/ARWGIM9G_r8/photo.jpg
          url: https://maps.google.com/maps/@?api=1&map_action=map&center={{ state_attr('device_tracker.google_maps_104688658658376260645', 'latitude') }},{{ state_attr('device_tracker.google_maps_104688658658376260645', 'longitude') }}&zoom=17
          tag: nizmo-location-info
    - service: notify.hangouts
      data_template:
        message: >
          Current location: {{ state_attr('device_tracker.google_maps_104688658658376260645', 'address') }}
        title: Michał is out from work
  - id: michal_entered_the_home
    alias: Michał entered the home
    initial_state: 'true'
    trigger: 
    - platform: state
      entity_id: person.michal # device_tracker.google_maps_104688658658376260645 #Nizm0
      to: home
      # event: enter
    condition:
    action: 
    - service: notify.push_to_chrome
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
        title: Michał entered the home
    - service: notify.hangouts
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
        title: Michał entered the home
        data:
          tag: nizmo-location-info
  - id: 589437twnoe86ogw6pw
    alias: Time to go home
    initial_state: 'true'
    trigger:
    - platform: numeric_state
      entity_id: sensor.nizm0_today_at_work
      above: 8
    condition:
    - condition: zone
      entity_id: device_tracker.google_maps_104688658658376260645
      zone: zone.work
    action:
    - service: notify.push_to_chrome_nizm0_oneplus3
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
        title: Michał it's time to leave
        data:
          tag: nizmo-location-info