automation:
  - id: portex_entered_the_home
    alias: Krzychu entered the home
    initial_state: 'true'
    trigger: 
    - platform: zone
      entity_id: device_tracker.portex
      zone: zone.home
      event: enter
    condition:
    action: 
    - service: notify.push_to_chrome_nizm0_oneplus3
      data_template:
        message: >
          New value is: {{ trigger.to_state.state }}
        title: Michał entered the home
        data:
          title: Michał entered the home
          tag: portex_notification
