automation:
  - id: 6ebec726-4af1-4d04-a0a2-ba191ab6c892
    alias: Krzychu entered the home
    initial_state: 'true'
    trigger: 
    - platform: zone
      entity_id: device_tracker.portex
      zone: zone.home
      event: enter
    condition:
    action: 
    - service: notify.push_to_chrome_nizm0_oneplus3
      data_template:
        message: >
          ({{states('sensor.date_time_iso')}})
          New value is: {{ trigger.to_state.state }}
        title: Portex entered the home
        data:
          title: Portex entered the home
          tag: portex_notification
