- platform: template
  switches:
    my_computer:
      friendly_name: "My Computer"
      value_template: "{{ is_state('binary_sensor.my_computer_connected', 'on') }}"
      turn_on:
        service: script.my_computer_wake
      turn_off:
        service: script.my_computer_shutdown
      icon_template: mdi:laptop