- platform: philips_ambilight+hue
  name: Ambilight+hue
  host: 192.168.1.130
  username: !secret philips_user
  password: !secret philips_pass
  scan_interval: 5
# - platform: philips_ambilight+yeelight
#   name: Lounge Lamp (Top Right) # (Name in Front-End)
#   host: 192.168.1.130 # (the TV)
#   username: !secret philips_user
#   password: !secret philips_paphilips_passsword
#   address: 192.168.1.XXX # (The Bulb)
#   display_options: right-top