vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.150
    name: Rockrobo
    token: !secret xiaomi_rockrobo_key

input_boolean:
  ready_to_vacuum:
    name: Flor is ready to vacuum
    icon: mdi:robot-vacuum
    # initial: off
    # restore_state:

input_datetime:
  vacuum_day_time:
    name: Vacuum date time
    has_date: false
    has_time: true
    # initial: '15:00'

switch:
  - platform: template
    switches:
      rockrobo_switch:
        entity_id: vacuum.rockrobo
        value_template: "{{ is_state('vacuum.rockrobo', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          data:
            entity_id: vacuum.rockrobo
        turn_off:
          service: vacuum.stop
          data:
            entity_id: vacuum.rockrobo

automation:
  - alias: Vacuum monitoring system for sensors
    id: vacuum_monitoring_system_for_sensors
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'sensor_dirty_left', 5) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Clean sensors in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'

  - alias: Vacuum monitoring system for filters
    id: vacuum_monitoring_system_for_filters
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'filter_left', 10) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Replace filter in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'

  - alias: Vacuum monitoring system for brushes
    id: vacuum_monitoring_system_for_brushes
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'side_brush_left', 10) %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'main_brush_left', 10) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Replace side or main brush in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'