automation:
  - alias: Vacuum monitoring system for sensors
    id: vacuum_monitoring_system_for_sensors
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'sensor_dirty_left', 5) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Clean sensors in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'

  - alias: Vacuum monitoring system for filters
    id: vacuum_monitoring_system_for_filters
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'filter_left', 10) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Replace filter in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'

  - alias: Vacuum monitoring system for brushes
    id: vacuum_monitoring_system_for_brushes
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'side_brush_left', 10) %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('vacuum.rockrobo', 'main_brush_left', 10) %}true{% endif %}"
    action:
    - service: calendar.todoist_new_task
      data_template:
        content: "Replace side or main brush in vacuum rockrobo"
        priority: 2
        due_date_string: 'today'