automation:
  - alias: Play Fireplace on tv
    id: 6d97032f-7771-485d-ac43-77cf9e6cffa0
    initial_state: false
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_2
          event: 1002
    action:
      - data:
          media_content_id: https://www.youtube.com/watch?v=Ux8xAuQBdkk
          media_content_type: video/youtube
        entity_id:
          - media_player.living_room_tv_cast
          # - media_player.tv_bathroom
        service: media_extractor.play_media
