- platform: workday
  country: PL
  workdays: [mon, tue, wed, thu, fri]
- platform: bayesian
  name: In bed
  prior: 0.1
  probability_threshold: 0.8
  observations:
    # - entity_id: 'binary_sensor.corridor_motion_sensor'
    #   prob_given_true: 0.8
    #   prob_given_false: 0.3
    #   platform: 'state'
    #   to_state: 'off'
    # - entity_id: 'binary_sensor.living_room_motion_sensor'
    #   prob_given_true: 0.8
    #   prob_given_false: 0.3
    #   platform: 'state'
    #   to_state: 'off'
    - entity_id: binary_sensor.desctop_pc
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'off'
    - entity_id: media_player.philips_tv
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'off'
    - entity_id: group.all_devices  # device_tracker.google_maps_104688658658376260645
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    # - entity_id: device_tracker.google_maps_109218123589188227395
    #   prob_give_true: 0.7
    #   prob_give_false: 0.7
    #   platform: 'state'
    #   to_state: 'home'
    - entity_id: 'sun.sun'
      prob_given_true: 0.7
      prob_given_false: 0.5
      platform: 'state'
      to_state: 'below_horizon'
- platform: ping
  name: Desctop PC
  host: 192.168.1.100
  count: 4
  scan_interval: 60
- platform: ping
  name: Router
  host: 192.168.1.1
  count: 4
  scan_interval: 60
- platform: ping
  name: Server
  host: 192.168.1.200
  count: 4
  scan_interval: 60