- platform: tomato
  host: !secret tomato_ip
  username: !secret tomato_username
  password:  !secret tomato_password
  http_id: !secret tomato_http_id
  interval_seconds: 10
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False

# - platform: gpslogger

- platform: google_maps
  username: !secret google_maps_login
  password: !secret google_maps_password
  max_gps_accuracy: 100


- platform: bluetooth_tracker
  request_rssi: true
#   device_id: 0
# - platform: bluetooth_le_tracker
#   track_new_devices: False
# - platform: ping
#   interval_seconds: 60
#   hosts:
#     gaming_pc: 192.168.1.100
#   count: 4