# - platform: owntracks_http
#   max_gps_accuracy: 200
#   waypoints: True
#   # mqtt_topic: "owntracks/#"
#   events_only: True
#   waypoint_whitelist:
#     - Nizm0
#     - Gosia
#     - Tablet1
#   region_mapping:
#     cabin: home
#     office: work
#     kindergarden: kindergarden
#     nursery: nursery
#     mp: mp
#     gp: gp
- platform: tomato
  host: !secret tomato_ip
  username: !secret tomato_username
  password:  !secret tomato_password
  http_id: !secret tomato_http_id
  interval_seconds: 10
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False
- platform: gpslogger

- platform: google_maps
  username: !secret google_maps_login
  password: !secret google_maps_password
  max_gps_accuracy: 100