- platform: yeelight
  devices:
    192.168.1.111:
      name: bedroom_main_light
      transition: 10
      use_music_mode: true #(defaults to False)
      save_on_change: true #(defaults to True)
# - platform: template
#   lights:
#     kids_light:
#       icon: mdi:lightbulb
#       value_template: "{{ is_state('input_boolean.kids_light', 'on') }}"
#       value_template: "off"
#       initial: off
#       turn_on:
#         service: light.turn_on
#         data: 
#           entity_id: switch.kids_light
#       turn_off:
#         service: light.turn_off
#         data:
#           entity_id: switch.kids_light