- platform: cast
  host: 192.168.1.130
  # name: Living room Android Tv Philips
- platform: gpmdp
  host: 192.168.1.100
  name: Pc_gpmdp
- platform: cast
  host: 192.168.1.131
  # name: Living room Google Home Mini
# - platform: broadlink
#   name: Living room TV
#   host: 192.168.1.51
#   mac: 78:0F:77:00:6A:7D
#   ircodes_ini: 'broadlink_media_codes/philips.ini'
#   ping_host: 192.168.1.46

- platform: philips_2016
  name: Philips TV
  host: 192.168.1.130
  mac: 3C:A0:67:E0:3E:E1
  username: !secret philips_user
  password: !secret philips_pass