- platform: cast
  host: 192.168.1.130
  # name: Office Android Tv Philips
- platform: gpmdp
  host: 192.168.1.100
  name: pc_gpmdp
- platform: cast
  host: 192.168.1.131
  # name: Office Google Home Mini
# - platform: broadlink
#   name: Office TV
#   host: 192.168.1.51
#   mac: 78:0F:77:00:6A:7D
#   ircodes_ini: 'broadlink_media_codes/philips.ini'
#   ping_host: 192.168.1.46
# - platform: philips_2016
#   name: phTV
#   host: 192.168.1.130
#   username: !secret philips_user
#   password: !secret philips_pass
- platform: universal
  name: Philips TV
  children:
    - media_player.phTV
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.phtvir