- alias: Play pause
  id: play_pause
  trigger:
    platform: event
    event_type: click
    event_data:
      event_id: binary_sensor.office_switch
      click_type: long_click_press
  action:
  - service: media_player.media_pause
    entity_id: media_player.pc_gpmdp
- alias: Play next
  id: play_next
  trigger:
    platform: event
    event_type: click
    event_data:
      event_id: binary_sensor.office_switch
      click_type: single
  action:
  - service: media_player.media_next_track
    entity_id: media_player.pc_gpmdp
- alias: Play previous
  id: play_previous
  trigger:
    platform: event
    event_type: click
    event_data:
      event_id: binary_sensor.office_switch
      click_type: double
  action:
  - service: media_player.media_previous_track
    entity_id: media_player.pc_gpmdp