- alias: Home door opened
  id: home_door_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_opened


#### HOME DOOR CLOSED
- alias: Home door closed
  id: home_door_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'off'
  condition:
    - platform: state
      entity_id: binary_sensor.corridor_motion_sensor
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_closed