- alias: Home door opened
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_opened


#### HOME DOOR CLOSED
- alias: Home door closed
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_closed