- alias: Home door opened
  id: home_door_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_opened
    - service: notify.push_to_chrome
      data_template:
        {% if is_state("group.all_devices", "not_home") and
              is_state("input_select.home_preset", "empty") -%}
          message: Nobody is in home
          icon: mdi:alert
        {%- else -%}
          message: "Home presence is: {{ states.group.all_devices.state }}"
        {%- endif %}
        title: Someone opened home doors
        data:
          actions:
            - action: open
              icon: "/static/icons/favicon-192x192.png"
              title: Open Home Assistant
            - action: open_door
              title: Open door
          data:
            tag: 'home-door-notification'


#### HOME DOOR CLOSED
- alias: Home door closed
  id: home_door_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.corridor_motion_sensor
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: script.home_doors_has_been_closed
- alias: Home door closed notification
  id: home_door_closed_notification
  trigger:
    - platform: state
      entity_id: binary_sensor.home_door_sensor
      to: 'off'
  action:
    - service: notify.push_to_chrome
      data_template:
        message: >
          Doors was open for: {{ trigger.for }} seconds {{ trigger.from_state.attributes['Open since'] }}
        title: Dors are now closed
        data:
          actions:
            - action: open
              icon: "/static/icons/favicon-192x192.png"
              title: Open Home Assistant
            - action: open_door
              title: Open door
          data:
            tag: 'home-door-notification'