### Living room
- alias: Living room top light turned on
  id: living_room_top_light_turned_on
  trigger:
  - platform: state
    entity_id: light.top_light
    to: 'on'
    for:
      seconds: 3
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.directional_light
      state: 'on'
    - condition: state
      entity_id: light.general_light
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: light.directional_light
  - service: homeassistant.turn_off
    entity_id: light.general_light

- alias: Living room light 1 and 2 turned on
  id: living_room_light_1_and_2_turned_on
  trigger:
  - platform: state
    entity_id: light.directional_light, light.general_light
    to: 'on'
    for:
      seconds: 3
  condition:
  - condition: state
    entity_id: light.top_light
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: light.top_light

### Bedroom
- alias: Turn on bedroom main light to red 10%
  id: turn_on_bedroom_main_light_to_red_10%
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      event_id: binary_sensor.bedroom_switch
      click_type: single
  condition:
  - condition: state
    entity_id: light.bedroom_main_light
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bedroom_main_light
      color_name: red
      brightness_pct: 5
- alias: Turn off bedroom main light
  id: turn_off_bedroom_main_light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      event_id: binary_sensor.bedroom_switch
      click_type: single
  condition:
  - condition: state
    entity_id: light.bedroom_main_light
    state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.bedroom_main_light
- alias: Turn on bedroom main light to wite 100%
  id: turn_on_bedroom_main_light_to_wite_100%
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      event_id: binary_sensor.bedroom_switch
      click_type: double
  # condition:
  #   - condition: state
  #     entity_id: light.bedroom_main_light
  #     state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bedroom_main_light
      white_value: 255
      brightness: 255
      kelvin: 2700
