- alias: Notify when temperature is to hight or to low
  id: notify_when_temperature_is_to_hight_or_to_low
  initial_state: 'true'
  trigger:
    platform: state
    entity_id:
    - sensor.bedroom_temperature
    - sensor.living_room_temperature
    - sensor.kitchen_temperature
    - sensor.bathroom_temperature
    - sensor.kids_temperature
  condition:
    - condition: template
      value_template: '{{ (trigger.to_state.state > states.input_number.temp_max.state or trigger.to_state.state < states.input_number.temp_min.state) and trigger.to_state.state != "unavailable" and trigger.to_state.state > 0}}'
  action:
    - service: notify.push_to_chrome
      data_template:
        message: "Temperature {{ trigger.to_state.state }} in {{ trigger.to_state.attributes.friendly_name }} and is out of demaded params"
        title: "Problem with Teperature in {{ trigger.to_state.attributes.friendly_name }}"
        data:
          tag: 'room_{{trigger.to_state.attributes.friendly_name}}_temp'