#############################################
#                                           #
#                 BW-SHP5                   #
#                                           #
#############################################
substitutions:
  # Modify variables based on your settings
  hostname: 'bw_shp5_01'
  plug_name: BW SHP5 01
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: ${hostname}
  platform: ESP8266
  board: esp8285
  on_boot:
    priority: -10
    # Turn on switch during startup
    then:
      - switch.turn_on: fakebutton

wifi:
  ssid: $ssid
  password: $password
  fast_connect: on

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  # password: "ABCD1234"
  reboot_timeout: 12h
web_server:
  port: 80

ota:
  # password: "ABCD1234"

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  # - platform: version
  #   name: ${plug_name} Version
  - platform: wifi_info
    ip_address:
      name: ${plug_name} Ip
    # ssid:
    #   name: ${plug_name} Ssid

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  # Uptime sensor
  - platform: uptime
    name: ${plug_name} Uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${plug_name} Wifi Signal
    update_interval: 30s
  # Power sensor
  - platform: cse7766
    update_interval: 10s
    # Current sensor
    current:
      name: ${plug_name} Current
      unit_of_measurement: A
      device_class: current
      accuracy_decimals: 3
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
            - 0.0 -> 0.0
            - 1.0 -> 0.4
            - 2.0 -> 1.2
            - 3.0 -> 2.0
            - 4.0 -> 3.0
            - 5.0 -> 4.0
        # Make everything below 0.01A appear as just 0A.
        # Furthermore it corrects 0.013A for the power usage of the plug.
#        - lambda: if (x < (0.01 - 0.013)) return 0; else return (x - 0.013);
    # Voltage sensor
    voltage:
      name: ${plug_name} Voltage
      unit_of_measurement: V
      device_class: voltage
      accuracy_decimals: 2
      filters:
        - multiply: 1.88
        # Map from sensor -> measured value
        # - calibrate_linear:
        #     - 0.0 -> 0.0
        #     - 100.0 -> 100.0
        #     - 200.0 -> 200.0
        #     - 300.0 -> 300.0
        #     - 400.0 -> 400.0
        #     - 500.0 -> 500.0
    # Power sensor
    power:
      id: power
      name: ${plug_name} Wattage
      unit_of_measurement: W
      device_class: power
      accuracy_decimals: 1
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
            - 0.0 -> 0.0
            - 1000.0 -> 1000.0
            - 2000.0 -> 2000.0
            - 3000.0 -> 3000.0
            - 4000.0 -> 4000.0
            - 5000.0 -> 5000.0
         # Make everything below 2W appear as just 0W.
         # Furthermore it corrects 1.14W for the power usage of the plug.
#        - lambda: if (x < (2 + 1.14)) return 0; else return (x - 1.14);
  # Total daily energy sensor
  - platform: total_daily_energy
    name: ${plug_name} Total Daily Energy
    power_id: power
    unit_of_measurement: kWh
    device_class: energy
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    icon: mdi:clock-alert

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: ${plug_name} Button
    pin:
      number: GPIO16
      inverted: true
    on_press:
      - switch.toggle: relay
    internal: true

switch:
  - platform: restart
    name: ${plug_name} Reboot
    id: hallway_lights_restart
  # Switch to toggle the relay (Power output)
  - platform: gpio
    id: relay
    # name: ${plug_name} Switch
    pin: GPIO14
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led
    restore_mode: ALWAYS_ON
  - platform: template
    name: ${plug_name} Switch
    optimistic: true
    restore_state: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
    turn_off_action:
      - switch.turn_off: relay
      - delay: 15s
      - switch.turn_on: relay

  # Switch to toggle the relay (USB output)
  - platform: gpio
    id: relay2
    name: ${plug_name} USB Switch
    pin: GPIO5
    restore_mode: RESTORE_DEFAULT_ON

output:
  # Relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a status indicator
status_led:
  pin:
    number: GPIO02
    inverted: true