substitutions:
  reboot_time: 5min
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: esp32_ble_tracker
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
  reboot_timeout: $reboot_time

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: $reboot_time

web_server:
  port: 80

ota:

# Example configuration entry
esp32_ble_tracker:
#   scan_interval: 300s

# binary_sensor:
#   - platform: esp32_ble_tracker
#     mac_address: C0:EE:FB:DB:B5:BA
#     name: "Nizm0 OnePlus3"

sensor:
  # - platform: ble_rssi
  #   mac_address: C4:7C:8D:66:CC:49
  #   name: "BLE Google Home Mini RSSI value"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6A:36:61
    temperature:
      name: "Xiaomi MiFlora Temperature 1"
    moisture:
      name: "Xiaomi MiFlora Moisture 1"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 1"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 1"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 1"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:66:CC:34
    temperature:
      name: "Xiaomi MiFlora Temperature 2"
    moisture:
      name: "Xiaomi MiFlora Moisture 2"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 2"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 2"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 2"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:66:CC:36
    temperature:
      name: "Xiaomi MiFlora Temperature 3"
    moisture:
      name: "Xiaomi MiFlora Moisture 3"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 3"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 3"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 3"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:66:DF:7C
    temperature:
      name: "Xiaomi MiFlora Temperature 4"
    moisture:
      name: "Xiaomi MiFlora Moisture 4"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 4"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 4"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 4"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6B:0B:6D
    temperature:
      name: "Xiaomi MiFlora Temperature 5"
    moisture:
      name: "Xiaomi MiFlora Moisture 5"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 5"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 5"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 5"
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6B:29:E3
    temperature:
      name: "Xiaomi MiFlora Temperature 6"
    moisture:
      name: "Xiaomi MiFlora Moisture 6"
    illuminance:
      name: "Xiaomi MiFlora Illuminance 6"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity 6"
    # battery_level:
    #   name: "Xiaomi MiFlora Battery Level 6"