substitutions:
  hostname: light_bedroom_001
  plug_name: Sonoff Bedroom Light
  entity_name: Bedroom Top Light
  reboot_time: 2min
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: $ssid
  password: $password
  fast_connect: on
  reboot_timeout: 120min

  ap:
    ssid: $hostname
    password: $password

time:
  - platform: homeassistant
    id: homeassistant_time

# Enable logging
logger:
web_server:
  port: 80
# Enable Home Assistant API
api:
  reboot_timeout: 120min
ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    # name: "Salon Light"
    id: switch1
    internal: true
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: ${entity_name} Switch
    optimistic: true
    id: fakebutton
    # internal: true
    turn_on_action:
    # - light.turn_on: light1
    - light.turn_off: led
    turn_off_action:
    # - light.turn_off: light1
    - light.turn_on: led
  # - platform: gpio
  #   id: relay
  #   pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_blue_led
    pin:
      number: GPIO13
      inverted: True
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: monochromatic
    # name: ${entity_name} LED
    output: basic_blue_led
    id: led
    internal: true
  - platform: binary
    name: $entity_name
    id: light1
    output: relay
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name} Uptime Sensor
    icon: mdi:clock-outline

