substitutions:
  hostname: 'shelly1_kids_top_light'
  reboot_time: 10min
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
  reboot_timeout: $reboot_time
api:
  reboot_timeout: $reboot_time
ota:
logger:
web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "SHelly1 Kids WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "SHelly1 Kids Uptime"
switch:
  - platform: restart
    name: "Reboot Kids Top Light"
    id: kids_top_ligts_restart

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO5
      mode: INPUT
      inverted: False
    name: Kids Light Swith
    internal: true
    on_state:
      then:
        - light.toggle: light1
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        - switch.turn_on: kids_top_ligts_restart

light:
  - platform: binary
    name: Top Light
    id: light1
    output: relay1
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: gpio
    pin: GPIO4
    id: relay1