substitutions:
  # Modify variables based on your settings
  hostname: 'sonof_pow_server_shelf'
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_time: 15min

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 100 # Highest priority, ensures light turns on without delay.
    then:
      # - switch.turn_off: fakebutton
      - delay: 10s
      - switch.turn_on: fakebutton

wifi:
  ssid: $ssid
  password: $password
  reboot_timeout: $reboot_time
  fast_connect: true

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: $reboot_time

web_server:
  port: 80

ota:

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: wifi_signal
    name: "Server Shelf WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Server Shelf Uptime"
  - platform: cse7766
    current:
      name: "Server Shelf Current"
    voltage:
      name: "Server Shelf Voltage"
    power:
      name: "Server Shelf Power"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Server Shelf Button"
    on_press:
      - switch.toggle: fakebutton
    internal: true

switch:
  - platform: template
    name: "Server Shelf Switch"
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
      - delay: 10s
      - switch.toggle: fakebutton
    # - switch.turn_on: relay
    # - light.turn_on: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Server Shelf Blue LED"
    output: pow_blue_led
    id: led