substitutions:
  # Modify variables based on your settings
  host_name: sonof_pow_server_shelf
  plug_name: Server Shelf
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_time: 15min

esphome:
  name: $host_name
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 100 # Highest priority, ensures light turns on without delay.
    then:
      - delay: 120s
      - if:
          condition:
            not:
              api.connected:
          then:
            - switch.turn_off: fakebutton
            - delay: 10s
            - switch.turn_on: fakebutton
          else:
            - switch.turn_on: fakebutton

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: $ssid
  password: $password
  reboot_timeout: $reboot_time
  fast_connect: true

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: $reboot_time

web_server:
  port: 80

ota:

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: wifi_signal
    name: ${plug_name} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${plug_name} Uptime
  - platform: cse7766
    current:
      name: ${plug_name} Current
      unit_of_measurement: A
      device_class: current
      accuracy_decimals: 3
      icon: mdi:flash-circle
    voltage:
      name: ${plug_name} Voltage
      unit_of_measurement: V
      device_class: voltage
      icon: mdi:flash-circle
    energy:
      name: "${plug_name} Energy"
      unit_of_measurement: "Wh"
      device_class: energy
      icon: mdi:flash-outline
    power:
      name: ${plug_name} Wattage
      id: power
      unit_of_measurement: W
      device_class: power
      icon: mdi:flash-circle
  - platform: total_daily_energy
    name: ${plug_name} Total Daily Energy
    power_id: ${host_name}_wattage
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert
    device_class: energy

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${plug_name} Button
    on_press:
      - switch.toggle: fakebutton
    internal: true

switch:
  - platform: template
    name: ${plug_name} Switch
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
      - delay: 15s
      - switch.toggle: fakebutton
      # - switch.turn_on: relay
      # - light.turn_on: led
  - platform: gpio
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: ${plug_name}  Blue LED
    output: pow_blue_led
    id: led
    internal: true