substitutions:
  hostname: sonoff_doorbell
  plug_name: Sonoff Doorbell
  entity_name: Doorbell
  reboot_time: 10min
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
  reboot_timeout: $reboot_time
api:
  reboot_timeout: $reboot_time
ota:
logger:
web_server:
  port: 80

sensor:
  # Uptime sensor
  - platform: uptime
    name: ${plug_name} Uptime
    icon: mdi:clock-outline
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${plug_name} Wifi Signal
    update_interval: 30s
    icon: mdi:wifi

switch:
  - platform: restart
    name: ${plug_name} Reboot
    id: hallway_lights_restart

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO4
      mode: INPUT
      inverted: False
    name: ${plug_name} Swith
    internal: true
    on_state:
      then:
        - light.toggle: light1
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        - switch.turn_on: hallway_lights_restart

light:
  - platform: binary
    name: ${entity_name}
    id: light1
    output: relay1
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    name: ${plug_name} LED
    output: pow_blue_led
    id: led
    internal: true

output:
  - platform: gpio
    pin: GPIO12
    id: relay1
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True