substitutions:
  plug_name: thermostat_d1mini
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: $plug_name
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: -10
    then:
      - switch.turn_off: relay

wifi:
  ssid: $ssid
  password: $password
  fast_connect: on
  reboot_timeout: 5min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $plug_name
    password: $password
web_server:
  port: 80

captive_portal:

switch:
  - platform: gpio
    name: "Thermostat On/Off"
    pin: GPIO5
    id: relay

dallas:
  - pin: GPIO0
    update_interval: 15s

sensor:
  - platform: dallas
    address: 0x628000002CCCB928
    name: "Thermostat Temperature"

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 2min

ota:
